export const AUTHENTICATION_COOKIE = 'AUTHENTICATION';
export const USER_INFO_COOKIE = 'USER_INFO';
export const PERMISSION_COOKIE = 'PERMISSION';
export const LOCALSTORAGE_PERMISSION = 'LOCALSTORAGE_PERMISSION';
