export type ProminerResourceDto = {
  calldepth: number;
  physical_name: string;
  logical_name: string;
  recycled: number;
  recycled_bo: number;
  recycled_so: number;
  resource_path: string;
  resource_type: string;
  loc: number;
  declaring_class: string;
  count: number;
  declaring_method: string;
  variable_name: string;
  variable_type: string;
  declared_type: string;
  field_type: string;
  field_name: string;
  sg_resource_id: string;
  app_resource_id: string;
  return_type: string;
  method_name: string;
  service_group_name: string;
  searchType: string;
  originClz: string;
  originMeth: string;
};

export type ProminerMethodDto = {
  calldepth: number;
  conditionDto: [];
  count: number;
  declaring_class: string;
  loc: number;
  method_name: string;
  physical_name: string;
  recycled: number;
  recycled_bo: number;
  recycled_so: number;
  resource_path: string;
  resource_type: string;
  return_type: string;
  service_group_name: string;
};
